#---
# spring:
#   config.activate.on-profile: default
# cds:
#   datasource:
#     auto-config.enabled: false
---
---
spring:
  config:
    activate:
      on-profile: sqlite
  datasource:
    url: "jdbc:sqlite:/db.sqlite"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
