---
spring:
  config.activate.on-profile: sqlite
  web.resources.static-locations: "file:./app/"
  jmx:
    enabled: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/db.sqlite
    hikari:
      maximum-pool-size: 1
---
spring:
  profiles.active: sqlite
