#---
# spring:
#   config.activate.on-profile: default
# cds:
#   datasource:
#     auto-config.enabled: false
---
spring:
  profiles: sqlite
  sql:
    init:
      mode: never
  datasource:
    url: "jdbc:sqlite:sqlite.db"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1

