#---
# spring:
#   config.activate.on-profile: default
# cds:
#   datasource:
#     auto-config.enabled: false
---
---
spring:
  config:
    activate:
      on-profile: sqlite
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: "jdbc:sqlite::resource:sqlite.db"
    hikari:
      maximum-pool-size: 1
cds:
  data-source:
    auto-config.enabled: false

